### ISSUE TITLE
MrTJPCoreMod java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by mrogaski** [AIE-Guild/AIE-Nomads-Modpack#106]
```
[12:28:20] [Client thread/ERROR] [FML]: There was a critical exception handling a packet on channel MrTJPCoreMod
java.lang.IndexOutOfBoundsException: readerIndex(15) + length(2) exceeds writerIndex(15): UnpooledHeapByteBuf(ridx: 15, widx: 15, cap: 15/15)
    at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1160) ~[AbstractByteBuf.class:?]
    at io.netty.buffer.AbstractByteBuf.readShort(AbstractByteBuf.java:581) ~[AbstractByteBuf.class:?]
    at codechicken.lib.packet.PacketCustom.readShort(PacketCustom.java:400) ~[PacketCustom.class:?]
    at codechicken.lib.packet.PacketCustom.readItemStack(PacketCustom.java:453) ~[PacketCustom.class:?]
    at codechicken.lib.packet.PacketCustom.readItemStack(PacketCustom.java:448) ~[PacketCustom.class:?]
    at mrtjp.projectred.exploration.TileBarrel.readDesc(TileBarrel.scala:80) ~[TileBarrel.class:?]
    at mrtjp.core.block.InstancedBlockTile.handleDescriptionPacket(tileblock.scala:516) ~[InstancedBlockTile.class:?]
    at mrtjp.core.handler.MrTJPCorePH.handleTilePacket(packethandlers.scala:31) ~[MrTJPCorePH.class:?]
    at mrtjp.core.handler.MrTJPCoreCPH$.handlePacket(packethandlers.scala:42) ~[MrTJPCoreCPH$.class:?]
    at codechicken.lib.packet.PacketCustom$ClientInboundHandler.handle(PacketCustom.java:100) ~[PacketCustom$ClientInboundHandler.class:?]
    at codechicken.lib.packet.PacketCustom$CustomInboundHandler.channelRead0(PacketCustom.java:77) ~[PacketCustom$CustomInboundHandler.class:?]
    at codechicken.lib.packet.PacketCustom$CustomInboundHandler.channelRead0(PacketCustom.java:64) ~[PacketCustom$CustomInboundHandler.class:?]
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
    at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
    at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273) [bje.class:?]
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602) [bao.class:?]
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
    at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
```

**Comment by mrogaski** [comment]
Unable to reproduce.
