### ISSUE TITLE
[1.0.2] Recurring server crash

### ISSUE THREAD

**Issue by mrogaski** [AIE-Guild/AIE-Nomads-Modpack#41]
```
Time: 6/13/15 7:30 AM
Description: Exception in server tick loop

java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
        at java.util.HashMap$KeyIterator.next(HashMap.java:1453)
        at net.minecraft.entity.EntityTracker.func_72788_a(EntityTracker.java:26
9)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.jav
a:648)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(Dedicated
Server.java:334)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.jav
a:547)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

```

**Comment by mrogaski** [comment]
Unable to reproduce.
