### ISSUE TITLE
[1.0.3] java.lang.NoSuchFieldError: texture

### ISSUE THREAD

**Issue by mrogaski** [AIE-Guild/AIE-Nomads-Modpack#59]
```
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 10/6/15 5:10 AM
Description: Ticking block entity

java.lang.NoSuchFieldError: texture
        at buildcraft.core.lib.EntityBlock.<init>(EntityBlock.java:21)
        at buildcraft.factory.FactoryProxy.newPumpTube(FactoryProxy.java:28)
        at buildcraft.factory.TilePump.createTube(TilePump.java:179)
        at buildcraft.factory.TilePump.func_145845_h(TilePump.java:83)
        at net.minecraft.world.World.func_72939_s(World.java:1939)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.jav
a:636)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(Dedicated
Server.java:334)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.jav
a:547)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
        at buildcraft.core.lib.EntityBlock.<init>(EntityBlock.java:21)
        at buildcraft.factory.FactoryProxy.newPumpTube(FactoryProxy.java:28)
        at buildcraft.factory.TilePump.createTube(TilePump.java:179)
        at buildcraft.factory.TilePump.func_145845_h(TilePump.java:83)

-- Block entity being ticked --
Details:
        Name: net.minecraft.src.buildcraft.factory.TilePump // buildcraft.factory.TilePump
        Block type: ID #833 (tile.pumpBlock // buildcraft.factory.BlockPump)
        Block data value: 0 / 0x0 / 0b0000
        Block location: World: (444,68,1321), Chunk: (at 12,4,9 in 27,82; contains blocks 432,0,1312 to 447,255,1327), Region: (0,2; contains chunks 0,64 to 31,95, blocks 0,0,1024 to 511,255,1535)
        Actual block type: ID #833 (tile.pumpBlock // buildcraft.factory.BlockPump)
        Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
        at net.minecraft.world.World.func_72939_s(World.java:1939)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

```

**Comment by mrogaski** [comment]
https://github.com/BuildCraft/BuildCraft/issues/3049

**Comment by mrogaski** [comment]
I build a copy of BuildCraft 7.1.8 and was able to start the test server without this error.  But we'll have to wait until a build > 7.1.6 is up on Curse.
