### ISSUE TITLE
[1.2.2] FML dependency issue

### ISSUE THREAD

**Issue by mrogaski** [AIE-Guild/AIE-Nomads-Modpack#98]
```
[20:44:53] [Client thread/INFO] [FML]: Forge Mod Loader has identified 184 mods to load
[20:44:53] [Client thread/INFO] [FML]: Found mod(s) [redgear_core] containing declared API package buildcraft.api.tools (owned by BuildCraftAPI|core) without associated API reference
[20:44:53] [Client thread/INFO] [FML]: Found mod(s) [catwalks, catwalkmod] containing declared API package buildcraft.api.tools (owned by BuildCraftAPI|core) without associated API reference
[20:44:53] [Client thread/INFO] [FML]: Found mod(s) [ExtraUtilities] containing declared API package baubles.api (owned by Baubles) without associated API reference
[20:44:53] [Client thread/INFO] [FML]: Found mod(s) [EnderIO] containing declared API package com.cricketcraft.chisel.api (owned by chisel) without associated API reference
[20:44:53] [Client thread/INFO] [FML]: Found mod(s) [redgear_core] containing declared API package cofh.api.block (owned by CoFHAPI) without associated API reference
[20:44:53] [Client thread/INFO] [FML]: Found mod(s) [EnderIO] containing declared API package mekanism.api (owned by Mekanism) without associated API reference
[20:44:53] [Client thread/INFO] [FML]: Found mod(s) [redgear_core] containing declared API package cofh.api.tileentity (owned by CoFHAPI) without associated API reference
[20:44:53] [Client thread/INFO] [FML]: Found mod(s) [EnderIO] containing declared API package mekanism.api.gas (owned by Mekanism) without associated API reference
[20:44:53] [Client thread/INFO] [FML]: Found mod(s) [EnderIO] containing declared API package mekanism.api.transmitters (owned by Mekanism) without associated API reference
[20:44:55] [Client thread/ERROR] [FML]: Mod Sorting failed.
[20:44:55] [Client thread/ERROR] [FML]: Visting node FMLMod:CoFHCore{1.7.10R3.0.3}
[20:44:55] [Client thread/ERROR] [FML]: Current sorted list : [Dummy Container (BeforeAll) @2145126394, Wrapped{mcp}, Wrapped{FML}, Wrapped{Forge}, Wrapped{Dummy Container (null) @333084627}, Wrapped{CodeChickenCore}, Wrapped{ImmibisMicroblocks}, Wrapped{ivtoolkit}, Wrapped{Micdoodlecore}, Wrapped{NotEnoughItems}, Wrapped{OpenComputers|Core}, Wrapped{PlayerAPI}, Wrapped{OpenModsCore}, Wrapped{<CoFH ASM>}, FMLMod:debug{1.0}, Dummy Container (Before) @2105802003, FMLMod:bspkrsCore{6.15}, FMLMod:StartingInventory{1.7.10.r03}, FMLMod:StatusEffectHUD{1.27}, FMLMod:Treecapitator{1.7.10}, FMLMod:ChickenShed{1.1.3}, FMLMod:appliedenergistics2{rv2-stable-10}, FMLMod:bdlib{1.9.4.109}, FMLMod:ae2stuff{0.5.0.56}, FMLMod:AppleCore{1.1.0}, FMLMod:ArchimedesShips{1.7.10 v1.7.1}, FMLMod:Backpack{2.0.1}, FMLMod:Baubles{1.0.1.10}, FMLMod:betterstorage{0.13.1.126}, FMLMod:BiblioCraft{1.11.4}, FMLMod:Mantle{1.7.10-0.3.2.jenkins191}, FMLMod:Natura{2.2.0}, FMLMod:BiomesOPlenty{2.1.0}, FMLMod:BiblioWoodsBoP{1.9}]
[20:44:55] [Client thread/ERROR] [FML]: Visited set for this node : [Wrapped{ImmibisMicroblocks}, FMLMod:ArchimedesShips{1.7.10 v1.7.1}, Wrapped{<CoFH ASM>}, Wrapped{CodeChickenCore}, Wrapped{OpenComputers|Core}, FMLMod:Baubles{1.0.1.10}, FMLMod:CoFHCore{1.7.10R3.0.3}, Wrapped{Forge}, FMLMod:StartingInventory{1.7.10.r03}, APIContainer{CoFHLib:1.7.10R1.0.3}, FMLMod:AppleCore{1.1.0}, APIContainer{CoFHAPI|energy:1.0}, FMLMod:bspkrsCore{6.15}, FMLMod:ae2stuff{0.5.0.56}, FMLMod:Natura{2.2.0}, Dummy Container (AfterAll) @2054977011, Dummy Container (Before) @2105802003, FMLMod:bdlib{1.9.4.109}, FMLMod:Backpack{2.0.1}, FMLMod:BiblioCraft{1.11.4}, APIContainer{CoFHAPI:1.7.10R1.0.13}, FMLMod:Treecapitator{1.7.10}, FMLMod:Mantle{1.7.10-0.3.2.jenkins191}, Wrapped{Micdoodlecore}, Wrapped{NotEnoughItems}, Wrapped{FML}, Wrapped{mcp}, Wrapped{OpenModsCore}, Dummy Container (BeforeAll) @2145126394, Dummy Container (After) @802144101, FMLMod:debug{1.0}, FMLMod:betterstorage{0.13.1.126}, Wrapped{Dummy Container (null) @333084627}, Wrapped{PlayerAPI}, FMLMod:Forestry{4.2.4.52}, FMLMod:BiomesOPlenty{2.1.0}, FMLMod:BiblioWoodsBoP{1.9}, FMLMod:BiblioWoodsForestry{1.7}, FMLMod:ChickenShed{1.1.3}, Wrapped{ivtoolkit}, FMLMod:StatusEffectHUD{1.27}, FMLMod:appliedenergistics2{rv2-stable-10}]
[20:44:55] [Client thread/ERROR] [FML]: Explored node set : [Wrapped{ImmibisMicroblocks}, FMLMod:ArchimedesShips{1.7.10 v1.7.1}, Wrapped{<CoFH ASM>}, Wrapped{CodeChickenCore}, Wrapped{OpenComputers|Core}, FMLMod:Baubles{1.0.1.10}, Wrapped{Forge}, FMLMod:StartingInventory{1.7.10.r03}, FMLMod:AppleCore{1.1.0}, FMLMod:bspkrsCore{6.15}, FMLMod:ae2stuff{0.5.0.56}, FMLMod:Natura{2.2.0}, Dummy Container (Before) @2105802003, FMLMod:bdlib{1.9.4.109}, FMLMod:Backpack{2.0.1}, FMLMod:BiblioCraft{1.11.4}, FMLMod:Treecapitator{1.7.10}, FMLMod:Mantle{1.7.10-0.3.2.jenkins191}, Wrapped{Micdoodlecore}, Wrapped{NotEnoughItems}, Wrapped{FML}, Wrapped{mcp}, Wrapped{OpenModsCore}, Dummy Container (BeforeAll) @2145126394, FMLMod:debug{1.0}, FMLMod:betterstorage{0.13.1.126}, Wrapped{Dummy Container (null) @333084627}, Wrapped{PlayerAPI}, FMLMod:BiomesOPlenty{2.1.0}, FMLMod:BiblioWoodsBoP{1.9}, FMLMod:ChickenShed{1.1.3}, Wrapped{ivtoolkit}, FMLMod:StatusEffectHUD{1.27}, FMLMod:appliedenergistics2{rv2-stable-10}]
[20:44:55] [Client thread/ERROR] [FML]: Likely cycle is in : [FMLMod:CoFHCore{1.7.10R3.0.3}, APIContainer{CoFHLib:1.7.10R1.0.3}, APIContainer{CoFHAPI|energy:1.0}, Dummy Container (AfterAll) @2054977011, APIContainer{CoFHAPI:1.7.10R1.0.13}, Dummy Container (After) @802144101, FMLMod:Forestry{4.2.4.52}, FMLMod:BiblioWoodsForestry{1.7}]
[20:44:55] [Client thread/ERROR] [FML]: A dependency cycle was detected in the input mod set so an ordering cannot be determined
[20:44:55] [Client thread/ERROR] [FML]: The first mod in the cycle is FMLMod:CoFHCore{1.7.10R3.0.3}
[20:44:55] [Client thread/ERROR] [FML]: The mod cycle involves
[20:44:55] [Client thread/ERROR] [FML]: FMLMod:CoFHCore{1.7.10R3.0.3} : before: [], after: [Forge@[10.13.3.1448,10.14)]
[20:44:55] [Client thread/ERROR] [FML]: APIContainer{CoFHLib:1.7.10R1.0.3} : before: [], after: [CoFHCore]
[20:44:55] [Client thread/ERROR] [FML]: APIContainer{CoFHAPI|energy:1.0} : before: [redgear_core, ExtraUtilities, FloodLights, EnderIO, bookshelf, CoFHCore, CompactMachines, bcadditions, Forestry, BuildCraft|Builders, BuildCraft|Transport, BuildCraft|Energy, BuildCraft|Silicon, BuildCraft|Robotics, BuildCraft|Core, BuildCraft|Factory], after: [CoFHCore]
[20:44:55] [Client thread/ERROR] [FML]: Dummy Container (AfterAll) @2054977011 : before: [], after: []
[20:44:55] [Client thread/ERROR] [FML]: APIContainer{CoFHAPI:1.7.10R1.0.13} : before: [endercore, CompactMachines, EnderIO, BuildCraft|Compat, bcadditions, FloodLights, ExtraUtilities, Forestry, bookshelf, redgear_core, BuildCraft|Builders, BuildCraft|Transport, BuildCraft|Energy, BuildCraft|Silicon, BuildCraft|Robotics, BuildCraft|Core, BuildCraft|Factory], after: [CoFHLib]
[20:44:55] [Client thread/ERROR] [FML]: Dummy Container (After) @802144101 : before: [], after: []
[20:44:55] [Client thread/ERROR] [FML]: FMLMod:Forestry{4.2.4.52} : before: [], after: [Forge@[10.13.4.1566,), Buildcraft|Core@[6.1.7,), ExtrabiomesXL, BiomesOPlenty, IC2@[2.0.140,), Natura@[2.2.0,), HardcoreEnderExpansion]
[20:44:55] [Client thread/ERROR] [FML]: FMLMod:BiblioWoodsForestry{1.7} : before: [], after: [BiblioCraft, Forestry]
[20:44:55] [Client thread/ERROR] [FML]: The full error
cpw.mods.fml.common.toposort.ModSortingException: There was a cycle detected in the input graph, sorting is not possible
    at cpw.mods.fml.common.toposort.TopologicalSort.explore(TopologicalSort.java:190) ~[TopologicalSort.class:?]
    at cpw.mods.fml.common.toposort.TopologicalSort.explore(TopologicalSort.java:199) ~[TopologicalSort.class:?]
    at cpw.mods.fml.common.toposort.TopologicalSort.explore(TopologicalSort.java:199) ~[TopologicalSort.class:?]
    at cpw.mods.fml.common.toposort.TopologicalSort.explore(TopologicalSort.java:199) ~[TopologicalSort.class:?]
    at cpw.mods.fml.common.toposort.TopologicalSort.explore(TopologicalSort.java:199) ~[TopologicalSort.class:?]
    at cpw.mods.fml.common.toposort.TopologicalSort.explore(TopologicalSort.java:199) ~[TopologicalSort.class:?]
    at cpw.mods.fml.common.toposort.TopologicalSort.explore(TopologicalSort.java:199) ~[TopologicalSort.class:?]
    at cpw.mods.fml.common.toposort.TopologicalSort.explore(TopologicalSort.java:199) ~[TopologicalSort.class:?]
    at cpw.mods.fml.common.toposort.TopologicalSort.explore(TopologicalSort.java:199) ~[TopologicalSort.class:?]
    at cpw.mods.fml.common.toposort.TopologicalSort.topologicalSort(TopologicalSort.java:145) ~[TopologicalSort.class:?]
    at cpw.mods.fml.common.toposort.ModSorter.sort(ModSorter.java:133) ~[ModSorter.class:?]
    at cpw.mods.fml.common.Loader.sortModList(Loader.java:272) [Loader.class:?]
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:493) [Loader.class:?]
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:208) [FMLClientHandler.class:?]
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480) [bao.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878) [bao.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
    at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
```

**Comment by mrogaski** [comment]
For clarity, here's the cycle.

```
[20:44:55] [Client thread/ERROR] [FML]: 
    APIContainer{CoFHAPI|energy:1.0} : 
        before: [
            redgear_core, 
            ExtraUtilities, 
            FloodLights,
            EnderIO,
            bookshelf,
            CoFHCore,
            CompactMachines,
            bcadditions,
            Forestry,
            BuildCraft|Builders,
            BuildCraft|Transport,
            BuildCraft|Energy,
            BuildCraft|Silicon,
            BuildCraft|Robotics,
            BuildCraft|Core,
            BuildCraft|Factory
        ], 
        after: [
            CoFHCore
        ]
```

**Comment by mrogaski** [comment]
Ran it again with a fresh pull from Curse and got a slightly different message.

```
[21:32:03] [Client thread/ERROR] [FML]: Visting node FMLMod:CoFHCore{1.7.10R3.0.3}
[21:32:03] [Client thread/ERROR] [FML]: Current sorted list : [Dummy Container (BeforeAll) @77563988, Wrapped{mcp}, Wrapped{FML}, Wrapped{Forge}, Wrapped{Dummy Container (null) @1660300724}, Wrapped{CodeChickenCore}, Wrapped{ImmibisMicroblocks}, Wrapped{ivtoolkit}, Wrapped{Micdoodlecore}, Wrapped{NotEnoughItems}, Wrapped{OpenComputers|Core}, Wrapped{PlayerAPI}, Wrapped{OpenModsCore}, Wrapped{<CoFH ASM>}, FMLMod:debug{1.0}, Dummy Container (Before) @2056684427, FMLMod:bspkrsCore{6.15}, FMLMod:StartingInventory{1.7.10.r03}, FMLMod:StatusEffectHUD{1.27}, FMLMod:Treecapitator{1.7.10}, FMLMod:ChickenShed{1.1.3}, FMLMod:appliedenergistics2{rv2-stable-10}, FMLMod:bdlib{1.9.4.109}, FMLMod:ae2stuff{0.5.0.56}, FMLMod:AppleCore{1.1.0}, FMLMod:ArchimedesShips{1.7.10 v1.7.1}, FMLMod:Backpack{2.0.1}, FMLMod:Baubles{1.0.1.10}, FMLMod:betterstorage{0.13.1.126}, FMLMod:BiblioCraft{1.11.4}, FMLMod:Mantle{1.7.10-0.3.2.jenkins191}, FMLMod:Natura{2.2.0}, FMLMod:BiomesOPlenty{2.1.0}, FMLMod:BiblioWoodsBoP{1.9}]
[21:32:03] [Client thread/ERROR] [FML]: Visited set for this node : [FMLMod:Mantle{1.7.10-0.3.2.jenkins191}, FMLMod:betterstorage{0.13.1.126}, FMLMod:BiblioWoodsForestry{1.7}, APIContainer{CoFHAPI:1.7.10R1.0.1}, FMLMod:StartingInventory{1.7.10.r03}, FMLMod:BiomesOPlenty{2.1.0}, FMLMod:BiblioWoodsBoP{1.9}, FMLMod:appliedenergistics2{rv2-stable-10}, FMLMod:Backpack{2.0.1}, Dummy Container (BeforeAll) @77563988, FMLMod:Baubles{1.0.1.10}, Wrapped{CodeChickenCore}, FMLMod:Natura{2.2.0}, Wrapped{ivtoolkit}, FMLMod:ae2stuff{0.5.0.56}, Wrapped{PlayerAPI}, Wrapped{Dummy Container (null) @1660300724}, FMLMod:Treecapitator{1.7.10}, FMLMod:ChickenShed{1.1.3}, FMLMod:AppleCore{1.1.0}, Wrapped{NotEnoughItems}, Dummy Container (Before) @2056684427, Wrapped{FML}, Wrapped{ImmibisMicroblocks}, Wrapped{OpenComputers|Core}, Dummy Container (AfterAll) @1099726, FMLMod:Forestry{4.2.4.52}, Wrapped{Micdoodlecore}, Wrapped{OpenModsCore}, FMLMod:debug{1.0}, FMLMod:CoFHCore{1.7.10R3.0.3}, Wrapped{<CoFH ASM>}, FMLMod:StatusEffectHUD{1.27}, FMLMod:bdlib{1.9.4.109}, APIContainer{CoFHAPI|energy:1.0}, Wrapped{mcp}, APIContainer{CoFHLib:1.7.10R1.0.3}, FMLMod:BiblioCraft{1.11.4}, Dummy Container (After) @697302005, Wrapped{Forge}, FMLMod:bspkrsCore{6.15}, FMLMod:ArchimedesShips{1.7.10 v1.7.1}]
[21:32:03] [Client thread/ERROR] [FML]: Explored node set : [FMLMod:Mantle{1.7.10-0.3.2.jenkins191}, FMLMod:betterstorage{0.13.1.126}, FMLMod:StartingInventory{1.7.10.r03}, FMLMod:BiomesOPlenty{2.1.0}, FMLMod:BiblioWoodsBoP{1.9}, FMLMod:appliedenergistics2{rv2-stable-10}, FMLMod:Backpack{2.0.1}, Dummy Container (BeforeAll) @77563988, FMLMod:Baubles{1.0.1.10}, Wrapped{CodeChickenCore}, FMLMod:Natura{2.2.0}, Wrapped{ivtoolkit}, FMLMod:ae2stuff{0.5.0.56}, Wrapped{PlayerAPI}, Wrapped{Dummy Container (null) @1660300724}, FMLMod:Treecapitator{1.7.10}, FMLMod:ChickenShed{1.1.3}, FMLMod:AppleCore{1.1.0}, Wrapped{NotEnoughItems}, Wrapped{FML}, Wrapped{ImmibisMicroblocks}, Dummy Container (Before) @2056684427, Wrapped{OpenComputers|Core}, Wrapped{Micdoodlecore}, Wrapped{OpenModsCore}, FMLMod:debug{1.0}, Wrapped{<CoFH ASM>}, FMLMod:StatusEffectHUD{1.27}, FMLMod:bdlib{1.9.4.109}, Wrapped{mcp}, FMLMod:BiblioCraft{1.11.4}, Wrapped{Forge}, FMLMod:bspkrsCore{6.15}, FMLMod:ArchimedesShips{1.7.10 v1.7.1}]
[21:32:03] [Client thread/ERROR] [FML]: 
    Likely cycle is in : [
        FMLMod:BiblioWoodsForestry{1.7},
        APIContainer{CoFHAPI:1.7.10R1.0.1},
        Dummy Container (AfterAll) @1099726,
        FMLMod:Forestry{4.2.4.52},
        FMLMod:CoFHCore{1.7.10R3.0.3},
        APIContainer{CoFHAPI|energy:1.0},
        APIContainer{CoFHLib:1.7.10R1.0.3},
        Dummy Container (After) @697302005
    ]
[21:32:03] [Client thread/ERROR] [FML]: A dependency cycle was detected in the input mod set so an ordering cannot be determined
[21:32:03] [Client thread/ERROR] [FML]: The first mod in the cycle is FMLMod:CoFHCore{1.7.10R3.0.3}
[21:32:03] [Client thread/ERROR] [FML]: The mod cycle involves
[21:32:03] [Client thread/ERROR] [FML]: FMLMod:BiblioWoodsForestry{1.7} : before: [], after: [BiblioCraft, Forestry]
[21:32:03] [Client thread/ERROR] [FML]: APIContainer{CoFHAPI:1.7.10R1.0.1} : before: [bcadditions, Forestry, EnderIO, ExtraUtilities, redgear_core, FloodLights, BuildCraft|Builders, BuildCraft|Transport, BuildCraft|Energy, BuildCraft|Silicon, BuildCraft|Robotics, BuildCraft|Core, BuildCraft|Factory, BuildCraft|Compat, bookshelf, CompactMachines, endercore], after: [CoFHLib]
[21:32:03] [Client thread/ERROR] [FML]: Dummy Container (AfterAll) @1099726 : before: [], after: []
[21:32:03] [Client thread/ERROR] [FML]: FMLMod:Forestry{4.2.4.52} : before: [], after: [Forge@[10.13.4.1566,), Buildcraft|Core@[6.1.7,), ExtrabiomesXL, BiomesOPlenty, IC2@[2.0.140,), Natura@[2.2.0,), HardcoreEnderExpansion]
[21:32:03] [Client thread/ERROR] [FML]: FMLMod:CoFHCore{1.7.10R3.0.3} : before: [], after: [Forge@[10.13.3.1448,10.14)]
[21:32:03] [Client thread/ERROR] [FML]: APIContainer{CoFHAPI|energy:1.0} : before: [redgear_core, Forestry, bcadditions, CoFHCore, EnderIO, CompactMachines, BuildCraft|Builders, BuildCraft|Transport, BuildCraft|Energy, BuildCraft|Silicon, BuildCraft|Robotics, BuildCraft|Core, BuildCraft|Factory, bookshelf, FloodLights, ExtraUtilities], after: [CoFHCore]
[21:32:03] [Client thread/ERROR] [FML]: APIContainer{CoFHLib:1.7.10R1.0.3} : before: [], after: [CoFHCore]
[21:32:03] [Client thread/ERROR] [FML]: Dummy Container (After) @697302005 : before: [], after: []
[21:32:03] [Client thread/ERROR] [FML]: The full error
```

**Comment by mrogaski** [comment]
DIsabled BiblioWoods: Forestry and the client loads.

**Comment by mrogaski** [comment]
This may be broader than Forestry, I've seen the issue with other paths.  Clearing out the dynamically loaded mods fixes the issue.

However, I'm leaving the BiblioWoods: Forestry package out because it prevents the use of some blocks in Forestry 4.
